In [2]:
import numpy as np
import math
weight1 = np.random.rand(3,4)
weight2 = np.random.rand(4,1)
print(weight1)
print(weight2)
training_input=np.array([[0,1,0],
                        [1,1,1],
                       [1,0,1],
                       [0,1,1]])
training_output=np.array([[0,1,1,0]]).T

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)
for i in range(15000):
    hidden_layer = sigmoid(np.dot(training_input,weight1))
    output_layer = sigmoid(np.dot(hidden_layer,weight2))
    d_weight2 = np.dot(hidden_layer.T, (2*(training_output - output_layer) * sigmoid_derivative(output_layer)))
    d_weight1 = np.dot(training_input.T,  (np.dot(2*(training_output - output_layer) * sigmoid_derivative(output_layer), weight2.T) * sigmoid_derivative(hidden_layer)))
    weight1+=d_weight1
    weight2+=d_weight2
print("after training")   
print(output_layer)    

[[0.77554806 0.20702323 0.01860736 0.69052358]
 [0.86027775 0.93905453 0.17585943 0.6560811 ]
 [0.29368112 0.41463186 0.04878642 0.17224258]]
[[0.64299845]
 [0.71831347]
 [0.52837794]
 [0.40269698]]
after training
[[0.00195727]
 [0.99631092]
 [0.99896968]
 [0.00319215]]
