In [ ]:
import torch 

In [ ]:
!pip install syft==0.2.5 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 378kB 11.3MB/s 
     |████████████████████████████████| 81kB 5.0MB/s 
     |████████████████████████████████| 20.1MB 68.4MB/s 
     |████████████████████████████████| 2.1MB 49.3MB/s 
     |████████████████████████████████| 3.9MB 14.6MB/s 
     |████████████████████████████████| 204kB 62.2MB/s 
     |████████████████████████████████| 491kB 41.1MB/s 
     |████████████████████████████████| 640.6MB 31kB/s 
     |████████████████████████████████| 61kB 4.0MB/s 
     |████████████████████████████████| 1.8MB 51.1MB/s 
     |████████████████████████████████| 71kB 4.5MB/s 
     |████████████████████████████████| 61kB 3.6MB/s 
     |████████████████████████████████| 61kB 3.9MB/s 
     |████████████████████████████████| 51kB 3.2MB/s 
  Created wheel for phe: filename=phe-1.4.0-py2.py3-none-any.whl size=37362 sha256=5f8710dc6b981833ae45f3187e67544d63cd06841d6ecd03c9c9fdc307c45dbe
  Stored i

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
dataset=load_iris()

In [ ]:
x=dataset.data
y=dataset.target

In [ ]:
import numpy as np
x=x.astype(float)

In [ ]:
x.shape

(150, 4)

In [ ]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
encoder= LabelEncoder()

In [ ]:
y1=encoder.fit_transform(y)

In [ ]:
y=pd.get_dummies(y1).values

In [ ]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [ ]:
y = list(map(float, y))

TypeError: ignored

In [ ]:
from torch.utils.data import Dataset

In [ ]:
class IRIS(Dataset):
  def __init__(self,images,labels,transform=None):
    self.data=images
    self.targets=labels
    self.to_torchtensor()
    self.transform = transform
  def to_torchtensor(self):
    self.data=torch.from_numpy(self.data).float()
    self.labels=torch.from_numpy(self.targets).float()
  def __len__(self):
    return len(self.data)
  def __getitem__(self, idx):
    sample=self.data[idx]
    target=self.targets[idx]
    if self.transform:
      sample = self.transform(sample)
    return sample,target 
  

In [ ]:
import syft as sy
hook = sy.TorchHook(torch)

In [ ]:
worker1 = sy.VirtualWorker(hook, id="worker1")
worker2 = sy.VirtualWorker(hook, id="worker2")

In [ ]:
class Arguments():
    def __init__(self):
        self.batch_size = 10
        self.test_batch_size = 10
        self.epochs =50
        self.lr = 0.001
        self.momentum = 0.5
        self.no_cuda = False
        self.seed = 1
        self.log_interval = 5
        self.save_model = False

args = Arguments()

use_cuda = not args.no_cuda and torch.cuda.is_available()

torch.manual_seed(args.seed)

device = torch.device("cuda" if use_cuda else "cpu")

kwargs = {'num_workers': 1, 'pin_memory': True} if use_cuda else {}

In [ ]:

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=7)

In [ ]:
x_train

tensor([[5.0000, 3.3000, 1.4000, 0.2000],
        [6.7000, 3.1000, 4.4000, 1.4000],
        [6.0000, 2.2000, 4.0000, 1.0000],
        [6.4000, 2.7000, 5.3000, 1.9000],
        [4.7000, 3.2000, 1.6000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.1000, 3.4000, 1.5000, 0.2000],
        [7.7000, 3.8000, 6.7000, 2.2000],
        [4.3000, 3.0000, 1.1000, 0.1000],
        [6.3000, 3.3000, 6.0000, 2.5000],
        [5.5000, 2.4000, 3.7000, 1.0000],
        [5.0000, 2.0000, 3.5000, 1.0000],
        [6.5000, 2.8000, 4.6000, 1.5000],
        [5.0000, 3.4000, 1.6000, 0.4000],
        [4.4000, 2.9000, 1.4000, 0.2000],
        [5.0000, 3.5000, 1.6000, 0.6000],
        [6.7000, 3.1000, 4.7000, 1.5000],
        [7.3000, 2.9000, 6.3000, 1.8000],
        [5.5000, 2.6000, 4.4000, 1.2000],
        [5.2000, 2.7000, 3.9000, 1.4000],
        [5.7000, 4.4000, 1.5000, 0.4000],
        [7.2000, 3.2000, 6.0000, 1.8000],
        [5.4000, 3.4000, 1.7000, 0.2000],
        [5.8000, 4.0000, 1.2000, 0

In [ ]:

federated_train_loader = sy.FederatedDataLoader(
                         IRIS(x_train,y_train)
                         .federate((worker1, worker2)),batch_size=args.batch_size)

In [ ]:
test_loader=torch.utils.data.DataLoader(IRIS(x_test,y_test), batch_size=args.batch_size)


In [ ]:
class Net(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(in_features=4, out_features=16)
    self.fc2 = nn.Linear(in_features=16, out_features=12)
    self.output = nn.Linear(in_features=12, out_features=3)
  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.output(x)
    return x

In [ ]:
import numpy as np
def train( args, model, device, train_loader, optimizer, epoch):
    train_loss=[]
    model.train()
    loss=0
    for batch_idx, (data, target) in enumerate(train_loader):
        model.send(data.location)
        data, target = data.to(device), target.to(device)
        output = model(data)
        loss= F.nll_loss(output, target).get()
        print("Epoch:", epoch, "Training Loss: ", loss.item())
        train_loss.append(loss.item())
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        model.get()
            

In [ ]:
def test( model, device, test_loader):
    test_loss=[]
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            loss =F.nll_loss(output, target)
            print("Epoch:", epoch, "Test Loss: ", loss.item())
           

    

In [ ]:
model = Net().to(device)
optimizer = optim.SGD(model.parameters(), lr=args.lr) 
for epoch in range(1, args.epochs + 1):
    
    train(args, model, device, federated_train_loader, optimizer, epoch)
    test(model,device,test_loader)
   
    



Epoch: 1 Training Loss:  0.3922111392021179
Epoch: 1 Training Loss:  0.5148643255233765
Epoch: 1 Training Loss:  0.362373411655426
Epoch: 1 Training Loss:  0.42786845564842224
Epoch: 1 Training Loss:  0.4195229113101959
Epoch: 1 Training Loss:  0.34590497612953186
Epoch: 1 Training Loss:  0.38483625650405884
Epoch: 1 Training Loss:  0.45342594385147095
Epoch: 1 Training Loss:  0.45700564980506897
Epoch: 1 Training Loss:  0.45152005553245544
Epoch: 1 Training Loss:  0.4558667540550232
Epoch: 1 Training Loss:  0.4727829694747925
Epoch: 1 Test Loss:  0.4807301461696625
Epoch: 1 Test Loss:  0.42843955755233765
Epoch: 1 Test Loss:  0.46474510431289673
Epoch: 1 Test Loss:  0.37971895933151245
Epoch: 1 Test Loss:  0.47564181685447693
Epoch: 2 Training Loss:  0.3922111392021179
Epoch: 2 Training Loss:  0.5148643255233765
Epoch: 2 Training Loss:  0.362373411655426
Epoch: 2 Training Loss:  0.42786845564842224
Epoch: 2 Training Loss:  0.4195229113101959
Epoch: 2 Training Loss:  0.3459049761295318

In [ ]:
[iuoiuo=p[]t]